/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiUserUserResponse
 */
export interface InternalApiUserUserResponse {
    /**
     * 
     * @type {number}
     * @memberof InternalApiUserUserResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InternalApiUserUserResponse
     */
    login?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InternalApiUserUserResponse
     */
    userRoles?: Array<string>;
}

/**
 * Check if a given object implements the InternalApiUserUserResponse interface.
 */
export function instanceOfInternalApiUserUserResponse(value: object): value is InternalApiUserUserResponse {
    return true;
}

export function InternalApiUserUserResponseFromJSON(json: any): InternalApiUserUserResponse {
    return InternalApiUserUserResponseFromJSONTyped(json, false);
}

export function InternalApiUserUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiUserUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'login': json['login'] == null ? undefined : json['login'],
        'userRoles': json['userRoles'] == null ? undefined : json['userRoles'],
    };
}

export function InternalApiUserUserResponseToJSON(json: any): InternalApiUserUserResponse {
    return InternalApiUserUserResponseToJSONTyped(json, false);
}

export function InternalApiUserUserResponseToJSONTyped(value?: InternalApiUserUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'login': value['login'],
        'userRoles': value['userRoles'],
    };
}

