/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalApiCatFileMetadata
 */
export interface InternalApiCatFileMetadata {
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatFileMetadata
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    key?: string;
    /**
     *
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    originalUrl?: string;
    /**
     *
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    previewUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatFileMetadata
     */
    size?: number;
    /**
     *
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalApiCatFileMetadata
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalApiCatFileMetadata
     */
    width?: number;
}

/**
 * Check if a given object implements the InternalApiCatFileMetadata interface.
 */
export function instanceOfInternalApiCatFileMetadata(value: object): value is InternalApiCatFileMetadata {
    return true;
}

export function InternalApiCatFileMetadataFromJSON(json: any): InternalApiCatFileMetadata {
    return InternalApiCatFileMetadataFromJSONTyped(json, false);
}

export function InternalApiCatFileMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiCatFileMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'key': json['key'] == null ? undefined : json['key'],
        'originalUrl': json['originalUrl'] == null ? undefined : json['originalUrl'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'size': json['size'] == null ? undefined : json['size'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function InternalApiCatFileMetadataToJSON(json: any): InternalApiCatFileMetadata {
    return InternalApiCatFileMetadataToJSONTyped(json, false);
}

export function InternalApiCatFileMetadataToJSONTyped(value?: InternalApiCatFileMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'key': value['key'],
        'originalUrl': value['originalUrl'],
        'previewUrl': value['previewUrl'],
        'size': value['size'],
        'thumbnailUrl': value['thumbnailUrl'],
        'type': value['type'],
        'url': value['url'],
        'width': value['width'],
    };
}

