/* tslint:disable */
/* eslint-disable */
/**
 * richmond-api
 * Backend for richmond app
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InternalApiUserRefreshRequest
 */
export interface InternalApiUserRefreshRequest {
    /**
     *
     * @type {string}
     * @memberof InternalApiUserRefreshRequest
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the InternalApiUserRefreshRequest interface.
 */
export function instanceOfInternalApiUserRefreshRequest(value: object): value is InternalApiUserRefreshRequest {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function InternalApiUserRefreshRequestFromJSON(json: any): InternalApiUserRefreshRequest {
    return InternalApiUserRefreshRequestFromJSONTyped(json, false);
}

export function InternalApiUserRefreshRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalApiUserRefreshRequest {
    if (json == null) {
        return json;
    }
    return {
        'refreshToken': json['refreshToken'],
    };
}

export function InternalApiUserRefreshRequestToJSON(json: any): InternalApiUserRefreshRequest {
    return InternalApiUserRefreshRequestToJSONTyped(json, false);
}

export function InternalApiUserRefreshRequestToJSONTyped(value?: InternalApiUserRefreshRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        'refreshToken': value['refreshToken'],
    };
}
